// <auto-generated />
using System;
using FinLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinLedger.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260114040100_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinLedger.Domain.Aggregates.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_Status_Valid", "\"Status\" IN ('Pending','Completed','Failed','Cancelled')");
                        });
                });

            modelBuilder.Entity("FinLedger.Domain.Aggregates.WebhookAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("WebhookAggregates", (string)null);
                });

            modelBuilder.Entity("FinLedger.Domain.Entities.EventStore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType");

                    b.HasIndex("AggregateId", "CreatedAt");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("FinLedger.Domain.Entities.ReconciliationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClearingBalance")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int>("CompletedPayments")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CustomerBalance")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int>("FailedPayments")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBalanced")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MerchantBalance")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PendingPayments")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPayments")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ReconciliationSnapshots", (string)null);
                });

            modelBuilder.Entity("FinLedger.Domain.Aggregates.Payment", b =>
                {
                    b.OwnsMany("FinLedger.Domain.Entities.LedgerEntry", "LedgerEntries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Account")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<int>("Credit")
                                .HasColumnType("integer");

                            b1.Property<int>("Debit")
                                .HasColumnType("integer");

                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TransactionHash")
                                .IsRequired()
                                .HasMaxLength(88)
                                .HasColumnType("character varying(88)");

                            b1.HasKey("Id");

                            b1.HasIndex("Account");

                            b1.HasIndex("PaymentId");

                            b1.HasIndex("PaymentId", "CreatedAt");

                            b1.ToTable("LedgerEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsOne("FinLedger.Domain.StronglyTypedIds.MerchantId", "MerchantId", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasMaxLength(36)
                                .HasColumnType("uuid")
                                .HasColumnName("MerchantId");

                            b1.HasKey("PaymentId");

                            b1.HasIndex("Value");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsOne("FinLedger.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsOne("FinLedger.Domain.ValueObjects.PaymentReference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Reference");

                            b1.HasKey("PaymentId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("LedgerEntries");

                    b.Navigation("MerchantId")
                        .IsRequired();

                    b.Navigation("Reference")
                        .IsRequired();
                });

            modelBuilder.Entity("FinLedger.Domain.Aggregates.WebhookAggregate", b =>
                {
                    b.OwnsMany("FinLedger.Domain.Entities.WebhookDelivery", "Deliveries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("EncryptedPayload")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsSuccessful")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false);

                            b1.Property<DateTime?>("LastAttemptAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("NextRetryAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("RetryCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0);

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("WebhookAggregateId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("NextRetryAt");

                            b1.HasIndex("PaymentId");

                            b1.HasIndex("WebhookAggregateId");

                            b1.ToTable("WebhookDeliveries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WebhookAggregateId");
                        });

                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
